
# Epilogue {.unnumbered}
It feels like we have come a long way since the first lecture about special relativity. Let's try to summarise the main steps we have made, before looking at how these ideas get generalized in further theories.

## Overview

In Part I and II, we considered how to write down expressions that are Lorentz invariant (for scalars), or covariant, taking on the same *form* in all inertial reference frames, following the principle of relativity, namely that all inertial frames should be equivalent for the formulation of physical laws. Following the invariance of the spacetime interval between two events, we developed our notion of 4-vectors and one-forms, whose components keep track of minus signs, based on the Minkowski metric $\eta_{\mu\nu}.$ We recognised that relativistic energy and momentum are related as the 4-momentum $P^{\mu},$ and that fields are continuous functions of spacetime, such as 4-velocity fields and 4-currents. The 4-momentum flux of a matter field is given by the symmetric, rank 2 stress energy tensor $T^{\mu\nu}_{\mathrm{matter}}.$

In Part III, we saw that the Lagrangian $L$ for a classical mechanical system with a finite number of degrees of freedom can be generalized to continuously many degrees of freedom, via a Lagrangian density $\mathcal{L},$ whose Euler-Lagrange equation is a PDE, involving space and time derivatives on an equal footing. In fact, if $\mathcal{L}$ is a Lorentz scalar, the Euler-Lagrange equation, on varying invariant or covariant field quantities, is itself relativistically covariant, automatically giving covariant field equations. This involves the divergence theorem in four dimensional spacetime, and the full solution of a problem requires specifying boundary conditions on a four-dimensional spacetime volume $\Omega.$

The d'Alembert equation (with wave speed $c$) is the simplest relativistic wave equation, and this in principle can be solved using Fourier methods with appropriate boundary conditions, and we identify the Fourier representation as a relativistic plane wave superposition. More complicated Lagrangians involve source terms (leading to inhomogeneous field equations), or higher-than-quadratic field combinations (leading to nonlinear equations).

We realized that conservation laws for fields correspond to finding 4-currents which are divergenceless, and proved Noether's theorem which finds such currents based on symmetry of $\mathcal{L}$ under some continuous symmetry of 'field space'. Separately, in the problems class, we saw that a similar argument makes the stress-energy tensor divergenceless when the field sees, through its Lagrangian, Minkowski spacetime as homogeneous.

In Part IV, we saw how Maxwell's equations could be put into a covariant form by realizing the components of $\boldsymbol{E}$ and $\boldsymbol{B}$ are components of the rank 2 antisymmetric Faraday tensor $F^{\mu\nu},$ and that there are two relativistic Maxwell equations. $V$ and $\boldsymbol{A}$ are naturally components of the 4-potential $A^{\mu},$ and electromagnetism can naturally be put into the Lagrangian framework if the varied field is the 4-potential itself. However, we do not have a full, fundamental Lagrangian approach to electrodynamics without a field theory for matter, which motivated us to consider very briefly relativistic quantum mechanics.

We now outline how many of these concepts generalize and are utilized in further fundamental theories of contemporary physics which you may well explore further next year in the **General Relativity** and **Quantum Fields and Particles** courses.

## Relativistic Quantum Mechanics
At the very end we saw that one way of constructing quantum mechanical matter field equations was to equate the action of the energy operator on a (relativistic) wavefunction with a relativistic expression for the energy in terms of the momentum operator acting on the wavefunction. Had we studied this in greater detail we would notice that the continuity of probability density is a conservation law related to the Noetherian symmetry of global gauge (phase) invariance of the wavefunction. Furthermore, when the quantum particle is charged, interactions with the electromagnetic field imply that gauge transformations of the electromagnetic potentials are related to a local gauge symmetry on the wavefunction.

We constructed the Klein-Gordon equation, which is like the d'Alembert equation with an extra term proportional to the particle's Compton wavenumber squared times the wavefunction. Although the KG equation has many desirable features for a relativistic quantum wave equation, we rejected it due to its being second order in time (so we cannot propagate it only knowing the initial wavefunction), and that the probability current arising from gauge transformations has a possibly negative density where we would expect to see a nonnegative probability density.

We very briefly looked at Dirac's approach of a multicomponent wavefunction, which in turn led to the definition of the Dirac equation in both Hamiltonian and relativistically covariant forms. Taking this work further would reveal that gauge transformations of the Dirac equation (involving the 4-component Dirac spinor $\psi$ and its adjoint $\overline{\psi}$) indeed now lead to a divergenceless 4-current whose 0-component is now positive definite. This is how Dirac proposed to resolve the paradox of negative energy states (which have their own plane wave solutions) with the idea of a 'sea' of filled negative energy states; now we interpret these negative energy states as related to antimatter. More detailed analysis can then show that when interactions are included, the Dirac equation, in the nonrelativistic limit, reduces the Pauli equation describing spin-1/2 particles. This work culminates in a Lagrangian describing a charged matter Dirac field and the electromagnetic field which are coupled by an interaction term involving the electromagnetic 4-potential and the Dirac 4-current derived from the Lorentz force Lagrangian. This "classical" field theory is the starting point for *quantum electrodynamics*.

## Further Special Relativity

The linear relativistic field equations we derived and discussed in the course can be put into the table below, depending on whether they include a mass or are massless, and according to their spin (i.e. the number of independent field components), ignoring interactions.

   spin                                                               massless equation                                                                                                                                  massive equation
  ------ -------------------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------
    0                                                                d'Alembert equation                                                                                                                              Klein-Gordon equation
                                                                    $\square^2\varphi = 0$                                                                                                      $\square^2\varphi + \left(\tfrac{m c}{\hbar}\right)^2 \varphi = 0$
   1/2                                                    massless Dirac ('neutrino'/Weyl) equation                                                                                                                       Dirac equation
                                                            $\gamma^{\mu}\partial_{\mu} \psi = 0$                                                                                              $\gamma^{\mu}\partial_{\mu} \psi + {\rm i} \tfrac{m c}{\hbar} \psi = 0$
    1                                                           Maxwell equation (homogeneous)                                                                                                                      Homogeneous Proca equation
                                                               $\partial_{\mu} F^{\mu\nu} = 0$                                                                                             $\partial_{\mu} F^{\mu\nu} + \left(\tfrac{m c}{\hbar}\right)^2 A^{\nu} = 0$
   3/2                                                        massless Rarita-Schwinger equation                                                                                                                massive Rarita-Schwinger equation
          $\gamma_{\nu} \partial_{\rho} \psi_{\sigma} + \gamma_{\rho} \partial_{\sigma} \psi_{\nu} + \gamma_{\sigma} \partial_{\nu} \psi_{\rho} = 0$   $\varepsilon^{\mu\nu\rho\sigma} \gamma^5 \gamma_{\nu} \partial_{\rho} \psi_{\sigma} + \tfrac{m c}{2\hbar}[\gamma^{\mu},\gamma^{\nu}] \psi_{\nu} = 0$
                                                                                                                                                      

In fact, if we were to continue, we would see the (empty space) Einstein equation for general relativity in the massless spin 2 slot, and the inhomogeneous form as the full Einstein field equation. Feynman, in the `Feynman Lectures on Gravitation`, shows how it is in principle possible to build up a classical field theory using symmetry arguments to show the relevant field is a massless, traceless symmetric rank 2 tensor (i.e. spin 2), and then forcing the resulting Lagrangian to be gauge invariant; the connection with the curvature of space is only made after the field equations are written down.

In fact, these field equations follow from the mathematical structure of the Poincaré group of all Lorentz transformations and spacetime translations. Using the representation theory of this group as matrices, Bargmann and Wigner (*Proc Nat Acad Sci USA* **34** (1948) 211-23) showed that each of the group's 'irreducible representations' are labelled by a continuous parameter (the mass $m$) and a discrete parameter (the spin), and there is a unique relativistic wave equation for each pair. For massive particles in their rest frame, the spin is equivalent to that of a nonrelativistic particle, and there are the same number of independent components. For massless 'particles' with null 4-momentum, however, the set of relevant Lorentz transformations keeping the state fixed is equivalent to the *2-dimensional euclidean group* (i.e. 2D rotations and translations), which leads to the restriction to only two spin states, parallel and antiparallel to the corresponding null vector: this accounts for why plane waves corresponding to massless fields (EM, gravity) are transverse to their direction of propagation.

One encounters particular difficulties in trying to derive a sensible physical interpretation from solutions of equations for massive particles when the spin gets high, beginning with the Rarita-Schwinger equation (introduced in *Phys Rev* **60** (1941) 61). As argued by Velo and Zwanziger (*Phys Rev* **186** (1969) 1137-41; **188** (1969) 2218-22), the wavefronts of a charged RS field, and other massive spin $> 1$ fields, can propagate faster than $c,$ in conflict with usual notions of causality. Thus matter fields appear to be mainly made up of Klein-Gordon, Proca and Dirac fields; in fact, the only fundamental massive particles in the standard model with spin 0 are Higgs bosons\.... It turns out that other fundamental interactions, beyond EM and gravity, can be explained using multicomponent generalizations of the gauge transformation relationship between the EM potential and the phase of a wavefunction: the corresponding classical wave equations are nonlinear, 'nonabelian' (i.e. matrix-valued) *Yang-Mills theories*, as discussed below.

## General Relativity

Einstein's original motivation for General Relativity was to widen the class of frames in which the formulation of physics is equivalent. Rather than only consider inertial frames, we now describe *all* frames of reference on spacetime -- 'general covariance'. Geometrically, this is equivalent to considering arbitrary curvilinear coordinates on spacetime, and the class of allowed transformations is widened to include any coordinate system. Each generalized frame/coordinate system is specified by a metric $g_{\mu\nu},$ which is now a tensor with respect to *all* coordinate transformations. In particular, $g_{\mu\nu}$ is now typically a function of position (representing the changing nature of the coordinates), and the coordinate axes are typically oblique, leading to a more complicated relationship between covariant and contravariant tensor components under the new class of transformations.

With this more general setup, physics can allow a description where the spacetime manifold itself might be curved (and therefore cannot not admit globally defined inertial frames). On a local scale, however, spacetime is assumed to be Minkowski: in a small neighbourhood of a spacetime event, a frame which looks locally inertial can always be found. Care is needed to have a tensorial notion of derivatives in this general setting (since derivatives $\partial_{\mu}$ depend on the geometry of the frame of reference); *covariant derivatives* $\nabla_{\mu}$ are properly tensorial, and defined as the usual spacetime derivatives in each event's local inertial frame. Formally, the covariant derivative is defined $$\nabla_{\mu} C^{\nu} = \partial_{\mu} C^{\nu} + \Gamma^{\nu}_{\mu \rho} C^{\rho},\quad \nabla_{\mu} C_{\nu} = \partial_{\mu} C_{\nu} - \Gamma^{\rho}_{\mu \nu} C_{\rho}.$$ The $\Gamma^{\nu}_{\mu \rho}$ are called *Christoffel symbols* or *connection coefficients*, and they are not themselves tensors; they can be found as coordinate derivatives of the metric tensor.

The covariant derivative bears some similarity to the gauge covariant derivative for a quantum matter field coupled to the EM field, although they are fundamentally different (and cannot be easily combined, leading to some of the difficulties in describing charged matter fields in GR). In particular, covariant derivatives do not commute, $$[\nabla_{\mu},\nabla_{\nu}]C^{\sigma} = R^{\sigma}_{\phantom{\sigma}\rho \mu\nu} C^{\rho},$$ where $R^{\sigma}_{\phantom{\sigma}\rho \mu\nu}$ is the *Riemann curvature tensor*, which is a rank 4 tensor expressing the curvature of spacetime. As a form of generalized curl, it satisfies a Bianchi identity $$\nabla_{\tau} R^{\sigma}_{\phantom{\sigma}\rho \mu\nu} + \nabla_{\mu} R^{\sigma}_{\phantom{\sigma}\rho \nu\tau} + \nabla_{\nu} R^{\sigma}_{\phantom{\sigma}\rho \tau\mu} = 0,$$ as well as several symmetries between its indices, leading to 20 independent components.

The contraction $R^{\sigma}_{\phantom{\sigma}\mu\sigma\nu}\equiv R_{\mu\nu}$ defines the symmetric *Ricci tensor* with 10 independent components, in turn whose contraction $R^{\mu}_{\phantom{\mu}\mu} \equiv R$ gives the *curvature scalar*. Einstein defined a curvature tensor $G^{\mu\nu} = R^{\mu\nu} - \tfrac{1}{2}g^{\mu\nu} R$ which is divergence-free, and the Einstein field equations are $$G^{\mu\nu} = \frac{8 \pi G}{c^4} T^{\mu\nu},$$ whose source term is the total stress-energy tensor of all energy-momentum (matter, EM fields, \...). This equation is nonlinear, and hence very difficult to solve in general.

In general relativity, gravity appears as a form of 'fictitious force' arising from choice of a non-inertial coordinate system. Other phenomena should be described in usual tensorial form, albeit with covariant derivatives; in GR, Maxwell's equations are written $$\nabla_{\mu} F_{\nu\rho} + \nabla_{\nu} F_{\rho\mu} + \nabla_{\rho} F_{\mu\nu} = 0, \qquad \nabla_{\mu}F^{\mu \nu} = \mu_0 J^{\nu}.$$

General Relativity can also be cast in a Lagrangian form, as originally suggested by Hilbert. The corresponding 'Einstein-Hilbert action' has a strikingly simple form: $$\mathcal{S} = \int (C R + \mathcal{L}) \sqrt{-g}{\rm d}^4 x,$$ where $C$ is a constant, $R$ is the curvature scalar, $\mathcal{L}$ is the Lagrangian density for matter and EM fields, and $g$ is the determinant of the metric tensor at each point. (In special relativity, we could ignore $\sqrt{-g}$ because the determinant of the Minkowski metric is always $-1.$) The Euler-Lagrange equations, on varying the metric tensor, give the correct Einstein field equations.

## Quantum Field Theory

Quantum field theory is a natural extension of this course: our approach to quantum matter fields did not include multiple quantum particles, which can only be described when 'fields are quantized'. This procedure is rooted in the fact that our relativistic field equations (with mass---and hence $\hbar$---or otherwise) are all classical PDEs, expressing equations of motion for field variables continuous over space and time.

In a fixed Lorentz frame, one can find wave fields oscillating at a fixed frequency $\omega$ with time dependence $\cos \omega t.$ *Quantizing the field* consists of quantizing this as a 'classical harmonic oscillator' (even if it is a quantum wave), giving, for each frequency $\omega,$ quantized energy (frequency) eigenstates $\hbar \omega (n+\tfrac{1}{2}),$ with a corresponding 'occupation number' $n.$ The ladder nature of the quantum harmonic oscillator spectrum implies going up (or down) by $N$ steps requires $N$ 'quanta' of $\hbar \omega,$ and for the EM field, these 'quantized field vibrations' are photons!

This procedure is sometimes called 'second quantization': we already had one Hilbert space describing the modes of the field, and now to each Fourier frequency $\omega$, we associate an extra harmonic oscillator Hilbert space! The quantized field excitations must satisfy the correct particle statistics on exchange (Bose-Einstein or Fermi-Dirac), and thus fermion field modes can only have an occupation number of 0 or 1. The quantization of free fields is straightforward, but not necessarily informative. Interactions must also be built in, and how this complicates matters is easier perhaps to see in the 'Lagrangian approach' to second quantization, rather than the Hamiltonian 'canonical field quantization' above.

The 'Lagrangian approach' is based on the path integral approach to quantum mechanics, where quantum probability amplitudes relating initial and final states are found by the sum $\sum_{\mathrm{all\,paths}}\exp\left(\frac{\rm i}{\hbar}\mathcal{S}\right).$ The paths consist of all possible sequences of values, over all times, that the degrees of freedom the corresponding classical Lagrangian $L$ may take, and this approach is completely dual to the usual Hamiltonian picture of Hilbert spaces, operators, etc. The classical equations of motion arise in the semiclassical limit, as the exponentials in the path sum oscillate very rapidly apart from when $\mathcal{S}$ does not change much when the path is varied, i.e. when the Euler-Lagrange equations are satisfied.

Now, classical fields have an action too, but rather than sum over all paths, we now take a *functional integral* over all *spacetime field configurations* which satisfy our given boundary conditions on our chosen spacetime volume $\Omega.$ Once again, the classical field equations arise when the action is stationary with respect to field variations, but now, there are always small fluctuations around, which are usually interpreted as particle-antiparticle pairs appearing in the vacuum (which also enters the canonical quantization picture from the 'zero point energy' $\hbar \omega/2$ for each frequency).

For 'Quantum Electrodynamics', the action is that corresponding to $\mathcal{L}_{\mathrm{QED}}$ as derived in the lectures. The free Dirac term, and the EM field term, are complicated but calculable, as the Lagrangian is quadratic in those terms, so the functional integral can be treated as a generalized Gaussian. However, the interactions, involving a cubic product of $\psi, \overline{\psi}$ and $A_{\mu},$ cannot be evaluated analytically. Nevertheless, since the coupling constant is small---it can be taken to be the dimensionless fine structure constant $\alpha = q^2/2\pi \varepsilon_0 \hbar c \approx 1/137$---the cubic term in the Lagrangian in the exponential can be Taylor expanded within the functional integral. The resulting series (with gaussians in the free field Lagrangians) can be interpreted combinatorially via 'Feynman diagrams', made up of 'interaction vertices', each one originating from the cubic interaction term in the full QED Lagrangian.

This theory has many mathematical problems which physicists have learned to get around or reinterpret, and all calculations are based on evaluating perturbation series. Nevertheless, precise experiments agree extremely well with quantum electrodynamic predictions, and the theory arises directly on generalizing classical relativistic field theory.

## Gauge Theories

The great success of QED inspired the quest to find alternative quantum field theories to describe the other two fundamental forces, the weak and strong nuclear forces, again starting with Lagrangian field theories. Given that protons and neutrons have very similar properties apart from charge, Heisenberg suggested that they were in fact two orthogonal 'isospin' states of some 2-spinor in the internal field space of a 'nucleon' particle. That is, instead of being independent Dirac particles, they are two components of an 'isospin doublet' $(p,n),$ and the corresponding Lagrangian should be invariant to $2\times 2$ unitary transformations of this 2-spinor, by analogy with the usual Lagrangian of a quantum wave being invariant to transformations of the complex phase.

However, it is not immediately obvious what sorts of fields/potentials arise from such nonabelian (i.e. noncommuting) gauge transformations of multicomponent fields. Yang and Mills (*Phys Rev* **96** (1954) 191-5) observed that, since all $N \times N$ unitary transformations can be represented by $U = \exp\left({\rm i} \sum_k \tau^k \ell_{k}\right),$ that is as exponentials of sets of generators $\ell_k$ (which are hermitian $N \times N$ matrices), nonabelian Yang-Mills potentials can be defined $A^k_{\mu} \ell_{k}$ (with the summation convention on $k$). These potential matrices couple to matter via generalizations of the gauge covariant derivative, and give rise to (nonlinear, nonabelian) 'fields' similar to the Faraday tensor.

The original attempts to describe the strong nuclear force with $2\times 2$ unitary matrices failed. However, in the 1960s, Gell-Mann showed that a generalization based on $3\times 3$ unitary transformations could describe the strong nuclear force in terms of quarks and colour interactions, and in the 1970s, Salam, Weinberg and Glashow showed that the weak force can be understood from an SU(2) $\times$ U(1) 'broken symmetry' from a larger invariance combined with electromagnetism, the 'electroweak force'.

## Final words ...
Although all of these further theories require generalizations, including curved spaces, operator-valued fields or matrix-valued potentials, they are rooted firmly in the language of relativistic field theory. I hope that your knowledge from this course of relativistically covariant fields, Lorentz invariant Lagrangians, Noetherian symmetries, etc, should help you in the future in trying to understand these fundamental theories of the universe!