# Example Class 3 {.unnumbered}

In this example class we will explore some novel features of relativistic kinematics.

We begin with a [Multiple choice quiz](./quiz/quiz_ec3.html). 

::: {.callout-caution icon="false"}
## {{< fa regular circle-question >}} Example exercise

**1. The relativistic particle mechanics** 

Given a particle with 4-velocity $U^\mu$ the 4-momentum is defined $P^{\mu} \equiv m c U^{\mu} = (\mathcal{E}/c,\underline{p}), where $\mathcal{E}$ is the relativistic energy and $\underline{p}$ is the relativistic 3-momentum.  Using this the 4-force is defined 
$$
    f^{\mu} \equiv c \frac{{\rm d} P^{\mu}}{{\rm d} s}.
$$ 
Show that *Minkowski's equation of motion* applies,
$$
    f^{\mu} U_{\mu} = 0.
$$
Suppose we write $f^{\mu} = \gamma(g, \underline{f})$ where $g$ is a scalar and $\underline{f}$ is a 3-vector.

(a) Write down an expression for $\underline{f}$ in terms of $\underline{p},$ and find an expression for $g$ in terms of $\underline{f}$ using the Minkowski equation. 

(b) Does $g$ agree with what you expect from the original definition of $f^{\mu}$?

(c) Can you explain why the Minkowski equation looks like the equation of circular motion in regular 3-vector mechanics? 
:::

::: {.content-hidden unless-meta="solutions.exampleclass3.display"}
::: {.callout-tip collapse="true" icon="false"}
## {{< fa regular circle-check >}} Solution

**1. The relativistic pole vaulter** 

Solution ...
:::
:::

::: {.callout-caution icon="false"}
## {{< fa regular circle-question >}} Example exercise

**2. The relativistic particle mechanics** 

We are interested in generalizing the Lagrangian approach to relativistic particle mechanics. Specifically, we seek a Lagrangian $L = L(x^{\mu},\dot{x}^{\mu})$ such that the Euler-Lagrange equations
$$\frac{\partial L}{\partial x^j} - \frac{\rm d}{{\rm d} t}\frac{\partial L}{\partial \dot{x}^j} = 0, \qquad j = 1,2,3,$$
where $\dot{\bullet} = \partial_t\bullet,$ gives us the relativistic equation of motion $f^j = m a^j$. Note that we do not necessarily expect the relativistic Lagrangian to have the form `KE $-$ PE' any more, since in relativity, energies occur as components of 4-momentum, but the Lagrangian is not a component of a 4-vector. We will assume that the action
$$
    \mathcal{S} \equiv \int_{t_0}^{t_1} L {\rm d} t,
$$ 
is Lorentz invariant. Show that with this assumption, $\gamma L$ is a Lorentz invariant on the particle's worldline.

Next, we want to determine the Lagrangian for a free particle, which experiences inertial motion with $a^{\mu} = 0,$ and we assume, by symmetry, that $\partial L/\partial x^{\mu} = 0$, meaning there are no spatially dependent fields acting on the particle. 

(a) Show that choosing $L$ to be $m \gamma c^2,$ the relativistic kinetic energy, does not give the required dependence. 

(b) Show that instead $L_{\mathrm{free}} \equiv -m c^2/\gamma$ is an appropriate choice for the free-particle Lagrangian. 

(c) Show that $\partial L/\partial \dot{x}^{j} = P^{j},$ thereby generalizing the classical expression for the canonical momentum.

(d) Does $L_{\mathrm{free}}$ transform correctly under Lorentz transformations?
:::

::: {.content-hidden unless-meta="solutions.exampleclass3.display"}
::: {.callout-tip collapse="true" icon="false"}
## {{< fa regular circle-check >}} Solution

**2. The relativistic pole vaulter** 

Solution ...
:::
:::